name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish GospelNet/GospelNet.csproj -c Release -o release --nologo
